global using AutoMapper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using OrderService.Contracts;
global using OrderService.Controllers.Base;
global using OrderService.Entities.Model;
global using OrderService.Entities.Model.DTOs;
global using OrderService.Exceptions.Error;
global using System.Collections.Generic;