// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Entities;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240322050153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Entities.Model.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID", "ProductID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OrderService.Entities.Model.CartCustomization", b =>
                {
                    b.Property<Guid>("CartID")
                        .HasColumnType("uuid");

                    b.Property<int>("CustomizationID")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartID", "CustomizationID");

                    b.ToTable("CartCustomizations");
                });

            modelBuilder.Entity("OrderService.Entities.Model.OrderDetails", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrdersOrderID")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Seq");

                    b.HasIndex("OrdersOrderID");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("OrderService.Entities.Model.OrderStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("StatusID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("StatusID");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            Name = "Submitted"
                        },
                        new
                        {
                            StatusID = 2,
                            Name = "Received"
                        },
                        new
                        {
                            StatusID = 3,
                            Name = " Picked up"
                        },
                        new
                        {
                            StatusID = 4,
                            Name = "Onway"
                        },
                        new
                        {
                            StatusID = 5,
                            Name = "Delivered"
                        });
                });

            modelBuilder.Entity("OrderService.Entities.Model.OrderTracking", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderStatusID")
                        .HasColumnType("bigint");

                    b.HasKey("Seq");

                    b.ToTable("OrderTracking");
                });

            modelBuilder.Entity("OrderService.Entities.Model.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .HasColumnType("bigint")
                        .HasColumnName("OrderID");

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<int>("DriverID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentID")
                        .HasColumnType("integer");

                    b.HasKey("OrderID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("OrderService.Entities.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("OrderService.Entities.Model.CartCustomization", b =>
                {
                    b.HasOne("OrderService.Entities.Model.Cart", null)
                        .WithMany("CartCustomization")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderService.Entities.Model.OrderDetails", b =>
                {
                    b.HasOne("OrderService.Entities.Model.Order", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdersOrderID");
                });

            modelBuilder.Entity("OrderService.Entities.Model.Cart", b =>
                {
                    b.Navigation("CartCustomization");
                });

            modelBuilder.Entity("OrderService.Entities.Model.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
